catalog/urls.py
from django.urls import path
from . import views

# The URLs and the associated views
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('download/', views.download, name='download'),
    path('firefox/', views.firefox_download, name='firefox'),
    path('chrome/', views.chrome_download, name='chrome'),
    path('edge/', views.edge_download, name='edge'),
    path('opera/', views.opera_download, name='opera'),
    path('add/', views.add, name='add'),
    path('articles/', views.ArticleBiasesByUserListView.as_view(), name='articles'),
    path('password/', views.change_password, name='change_password'),
]

news_checker_website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from catalog import views

# The URLs and the associated views
urlpatterns = [
    path('administrator_user_account_login/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('.well-known/pki-validation/7CAD372EF69C3A963E9161EBB719593E.txt', views.well_known),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create Article model (stores the article text and link)
class Article(models.Model):
    """Model representing an article."""
    url = models.CharField(max_length=300, help_text='Enter URL for article')
    text = models.TextField(help_text='Enter article text')

    def __str__(self):
        """String for representing the Model object."""
        return self.url

# Create ArticleBias model (stores the article, as well as the reader and their thoughts on it's bias)
class ArticleBias(models.Model):
    """Model representing the bias of an article."""
    article = models.ForeignKey('Article', on_delete=models.SET_NULL, null=True)
    bias = models.IntegerField()
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    used = models.BooleanField(default=False)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.article} ({self.bias})'

catalog/views.py
from django.shortcuts import render, redirect
from catalog.models import Article, ArticleBias
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
import os
from news_checker_website import settings
from django.http import HttpResponse
import json as simplejson
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

# Create your views here.
# Homepage view: sets the username cookie here (possibly change later?)
def index(request):
    # Renders page and gets response (so cookie can be set)
    response = render_to_response('index.html', {
        'authenticated': request.user.is_authenticated,
        'username': request.user.get_username()
    }, RequestContext(request))

    # Creates cookie used for extension
    if request.user.is_authenticated:
        response.set_cookie('news_checker_username', request.user.get_username())
    else:
        response.delete_cookie('news_checker_username')
    print(request.user.get_username())
    print(request.COOKIES.get('news_checker_username'))
    return response

# About page view
def about(request):
    return render(request, 'about.html')

# Download page view
def download(request):
    return render(request, 'download.html')

def firefox_download(request):
    zip_file = open(os.path.join(settings.STATIC_ROOT, 'zip/news_checker_extension_firefox.zip'), 'rb')
    response = HttpResponse(zip_file, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename="%s"' % 'news_checker_extension_firefox.zip'
    return response

def chrome_download(request):
    zip_file = open(os.path.join(settings.STATIC_ROOT, 'zip/news_checker_extension_chrome.zip'), 'rb')
    response = HttpResponse(zip_file, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename="%s"' % 'news_checker_extension_chrome.zip'
    return response

def edge_download(request):
    zip_file = open(os.path.join(settings.STATIC_ROOT, 'zip/news_checker_extension_chrome.zip'), 'rb')
    response = HttpResponse(zip_file, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename="%s"' % 'news_checker_extension_edge.zip'
    return response

def opera_download(request):
    zip_file = open(os.path.join(settings.STATIC_ROOT, 'zip/news_checker_extension_chrome.zip'), 'rb')
    response = HttpResponse(zip_file, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename="%s"' % 'news_checker_extension_opera.zip'
    return response

# Add view: adds an entry to the database here
@csrf_exempt
def add(request):
    # Gets message from extension (which redirects here)
    url = request.POST.get('url', '')
    text = request.POST.get('text', '')
    bias = request.POST.get('bias', '')
    username = request.POST.get('username', '')

    message = 'failed'
    to_return = dict()

    print(request.user.get_username())
    print("test")

    # Double checks that the url is set, and that the article is set. If the article doesn't exist, it creates it here.
    if url != '':
        bias = int(bias)
        try:
            article = Article.objects.get(url__exact=url)
        except:
            article = Article(url=url, text=text.replace("_", " "))
            article.save()
        try:
            article_bias = ArticleBias.objects.filter(article__exact=article).get(reader__exact=User.objects.get(username=username))
            used_status = article_bias.used
            article_bias.delete()
            article_bias = ArticleBias(article=article, bias=bias, reader=User.objects.get(username=username), used=used_status)
        except:
            article_bias = ArticleBias(article=article, bias=bias, reader=User.objects.get(username=username))
        article_bias.save()
        message = 'success'

    to_return['message'] = message
    if to_return['message'] == "success":
        return JsonResponse(to_return, status=200)
    else:
        return JsonResponse(to_return, status=314)

    # return render(request, 'add.html')

# Register view: Uses the UserForm to register a new user.
def register(request):
    if request.method == 'POST':
        f = UserForm(request.POST)
        if f.is_valid():
            f.save()
            return render(request, 'register_success.html')
    else:
        f = UserForm()
    return render(request, 'register.html', {'form': f})

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['username', 'email' ]

# View to list ArticleBiases readers make
class ArticleBiasesByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = ArticleBias
    template_name ='articlebias_list_user.html'
    paginate_by = 10

    def get_queryset(self):
        return ArticleBias.objects.filter(reader=self.request.user).order_by('used')

# Change password page
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form,
        'user': request.user
    })

def well_known(request):
    file = open(os.path.join(settings.STATIC_ROOT, 'txt/7CAD372EF69C3A963E9161EBB719593E.txt'), 'r')
    response = HttpResponse(file.read(), content_type='text/plain')
    response['Content-Disposition'] = 'inline;filename=7CAD372EF69C3A963E9161EBB719593E.txt'
    return response

catalog/templates/about.html
{% extends "base_generic.html" %}
<!--ABOUT PAGE HTML-->
{% block content %}
    <h1>About Us</h1>
    <h2>Mission</h2>
    <p>The News Checker Project was created to encourage news readers to have a deeper understanding of what they read. Given the importance of literacy and education in maintaining democracy, it's important to be aware of both implicit and intentional bias in news articles. I'm hoping that users will find this a useful tool to help them read the news thoughtfully.</p>
    <h2>Current Progress</h2>
    <p>As of right now, the News Checker Political Bias AI is in the training/debugging stages, as well as debugging the web extension. If you would like to contribute to training the AI, please download the extension <a href="{% url 'download' %}">here</a> and make a user account <a href="{% url 'register' %}">here</a>. If you would like to view the code behind the AI, click <a href="https://github.com/AnnabelleLew/political-bias-checker">here</a> to go to the GitHub repository.</p>
    <h2>Terms of Service</h2>
    <p>News Checker keeps track of the following data:</p>
    <list>
        <li class="about">Article biases submitted by the user</li>
        <li class="about">The username associated with the article bias</li>
        <li class="about">The email address used to register for an account</li>
    </list>
    <p>User accounts are being used to ensure that the data collected is not being purposefully skewed by individual users. User emails will be kept private and used exclusively to notify users of project updates. News Checker only collects data that users submit through the web extension, and the data collected will only be used for News Checker projects. Users will be notified and given the option to opt out before any data is sent to third parties. Cookies need to be enabled for the extension to work, since the extension uses cookies to check for which user is logged in. News Checker holds the right to terminate user accounts for any reason. If you believe your account has been terminated by mistake, please email me at news.checker.info@gmail.com.</p>
    <h2>Disclaimer</h2>
    <p>Please bear in mind that News Checker is not perfect. As the News Checker extension and website are both still being debugged, there may still be issues with both this website and the web extension. Any issues can be reported at news.checker.info@gmail.com.</p>
    <h2>Credits</h2>
    <p>Although the code was primarily written by Annabelle Lew, many aspects of the code used aspects of the Mozilla Developer tutorials for both Django and web extensions. In addition, the logo design was done by Kristen Lew. Finally, this entire website would not be on the Internet without the technical expertise of Norman Yung, as well as his permission to host the website on his server.</p>
{% endblock %}

catalog/templates/add.html
<!DOCTYPE html>
<!--ADDING ARTICLE BIAS TO DATABASE PAGE HTML-->
<html lang="en">
    <head>
        <title>News Checker</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <style>
            body {
                padding: 15px;
                background-color: #e9e8e3;
            }
        </style>
    </head>
    <body>
        <p>Article successfully added to our database! Thank you for contributing!</p>
        <a href="{% url 'index'%}" target="_blank" rel="noopener noreferrer">Click here to learn more about News Checker.</a>
    </body>
</html>

catalog/templates/articlebias_list_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Previously Read Articles</h1>
    <h3>All links redirect to news sources outside of this website.</h3>

    {% if articlebias_list %}
    <ul>
        {% for articlebias in articlebias_list %}
        <li>
            {% if articlebias.bias == -5 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Very strong left bias)</p>
            {% endif %}
            {% if articlebias.bias == -4 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Strong left bias)</p>
            {% endif %}
            {% if articlebias.bias == -3 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Left bias)</p>
            {% endif %}
            {% if articlebias.bias == -2 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Weak left bias)</p>
            {% endif %}
            {% if articlebias.bias == -1 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Very weak left bias)</p>
            {% endif %}
            {% if articlebias.bias == 0 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Unbiased)</p>
            {% endif %}
            {% if articlebias.bias == 1 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Very weak right bias)</p>
            {% endif %}
            {% if articlebias.bias == 2 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Weak right bias)</p>
            {% endif %}
            {% if articlebias.bias == 3 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Right bias)</p>
            {% endif %}
            {% if articlebias.bias == 4 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Strong right bias)</p>
            {% endif %}
            {% if articlebias.bias == 5 %}
                <p><a href="{{articlebias.article.url}}">{{articlebias.article.url}}</a> (Very strong right bias)</p>
            {% endif %}
        </li>
        {% endfor %}
    </ul>

    {% else %}
      <p>You haven't read any articles.</p>
    {% endif %}
{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<!--BASE TEMPLATE HTML-->
<html lang="en">
    <head>
        {% block title %}<title>News Checker</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <script type="text/javascript" language="javascript" src="{% static 'js/nav.js' %}"></script>
    </head>
    <body>
        {% block menubar %}
            <!--SIDEBAR FOR WEBPAGE-->
            <div class="menubar-nav">
                <a href="{% url 'index' %}" class="menu-text">News Checker</a>
                <div id="small-hidden-nav">
                    <a href="{% url 'about' %}" class="menu-text">About</a>
                    <a href="{% url 'download' %}" class="menu-text">Download</a>
                    {% if user.is_authenticated or authenticated %}
                        <a href="{% url 'articles' %}" class="menu-text">Article History</a>
                        <a class="menu-text" href="{% url 'change_password' %}">{{ user.get_username }}{{ username }}</a>
                        <a href="{% url 'logout'%}" class="menu-text">Logout</a>
                    {% else %}
                        <a href="{% url 'login'%}" class="menu-text">Login</a>
                    {% endif %}
                </div>
                <div id="icon" onclick="revealMenu(this)">
                    <div id="bar1"></div>
                    <div id="bar2"></div>
                    <div id="bar3"></div>
                </div>
            </div>
        {% endblock %}
        <!--CONTENT FOR WEBPAGE-->
        <div class="content">
            {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                <div class="pagination">
                    <p>
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                        {% endif %}
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                        {% endif %}
                    </p>
                </div>
                {% endif %}
            {% endblock %}
        </div>
    </body>
</html>

catalog/templates/change_password.html
{% extends "base_generic.html" %}
<!--REGISTRATION PAGE HTML-->
{% block title %}
<title>Profile</title>
{% endblock %}

{% block content %}
<h1>Profile</h1>
<div class="info">
    <h2>User info</h2>
    <table>
        <tr>
            <th><strong>Username</strong></th>
            <td>{{ user.get_username }}</td>
        </tr>
        <tr>
            <th><strong>Email</strong></th>
            <td>{{ user.email }}</td>
        </tr>
    </table>
</div>
<div class="login">
    <h2>Change password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Changes" />
    </form>
</div>
{% endblock %}

catalog/templates/download.html
{% extends "base_generic.html" %}
<!--DOWNLOAD PAGE HTML-->
{% block content %}
    <h1>Download</h1>
    <p>As of right now, the News Checker extension is still in development, so downloads can only be made directly from this website.</p>
    <h2>Firefox</h2>
    <p>Click <a href="{% url 'firefox' %}">here</a> to download the extension for Firefox. Once downloaded, go to <a href="about:debugging">about:debugging</a>, click on "Load Temporary Add-on", and click on the zip file in order to use it.</p>
    <h2>Chrome</h2>
    <p>Click <a href="{% url 'chrome' %}">here</a> to download the extension for Google Chrome. Once downloaded, unzip the file, go to <a href="chrome://extensions/">chrome://extensions</a>, turn on developer mode, click on "Load unpacked", and click on the unzipped folder (not the folder's contents) in order to use it.</p>
    <h2>Edge</h2>
    <p>Click <a href="{% url 'edge' %}">here</a> to download the extension for Microsoft Edge. Once downloaded, unzip the file, go to <a href="edge://extensions/">edge://extensions</a>, turn on developer mode, click on "Load unpacked", and click on the unzipped folder (not the folder's contents) in order to use it.</p>
    <h2>Opera</h2>
    <p>Click <a href="{% url 'opera' %}">here</a> to download the extension for Opera. Once downloaded, unzip the file, go to <a href="opera://extensions/">opera://extensions</a>, turn on developer mode, click on "Load unpacked", and click on the unzipped folder (not the folder's contents) in order to use it.</p>
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}
<!--HOMEPAGE HTML-->
{% load static %}
{% block content %}
    <table id="homepage">
        <tr>
            <td id="homepage-text-container">
                <h1 class="left-align-text">Read the news, smarter.</h1>
                <p class="left-align-text" style="font-size: 25px">The News Checker Project aims to encourage news readers to have a deeper understanding of what they read.</p>
                <a href="{% url 'about'%}"><input type="submit" value="Learn More" /></a>
            </td>
            <td id="homepage-img-container">
                <img src="{% static 'img/screenshot.png' %}" id="homepage-img" />
            </td>
        </tr>
    </table>
{% endblock %}

catalog/templates/register.html
{% extends "base_generic.html" %}
<!--REGISTRATION PAGE HTML-->
{% block title %}
<title>Create Account</title>
{% endblock %}

{% block content %}
<div class="login">
    <h1>Create Account</h1>
    <form method="post" >
        {% csrf_token %}
        {% for field in form %}
            <p>{{ field.label_tag }}</p>
            {{ field }}
            {% if field.help_text %}
                <p>{{ field.help_text }}</p>
            {% endif %}
            <br>
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <input type="submit" name="submit" value="Register" /></td>
    </form>
</div>
{% endblock %}

catalog/templates/register_success.html
{% extends "base_generic.html" %}
<!--SUCCESSFUL REGISTRATION FOR USER HTML-->
{% block content %}
    <p>Congratulations! You've successfully created an account.</p>
    <p><a href="{% url 'login' %}">Click here to log in</a></p>
{% endblock %}